-- Tossup database schema for a new Supabase project. Run in Supabase SQL Editor.
-- Seed the public catalog tables (themes, suggestions, option_collections,
-- result_messages) with your own content before starting a new installation.
create table if not exists public.themes (
  id integer generated by default as identity primary key,
  slug text not null unique,
  name text not null,
  symbol text not null,
  variants jsonb not null
);
create table if not exists public.suggestions (
  id integer generated by default as identity primary key,
  label text not null
);
create table if not exists public.option_collections (
  id integer generated by default as identity primary key,
  category text not null,
  name text not null,
  mode text not null,
  options jsonb not null
);
create table if not exists public.result_messages (
  id integer generated by default as identity primary key,
  message text not null,
  animation text not null
);
create table if not exists public.presets (
  id integer generated by default as identity primary key,
  user_id text not null,
  name text not null,
  options jsonb not null,
  created_at timestamptz default now()
);
create table if not exists public.newsletter_consents (
  user_id text primary key,
  email text not null,
  provider text not null,
  status text not null,
  consented_at timestamptz default now()
);

-- Public catalogs may be read anonymously, never changed via the public key.
alter table public.themes enable row level security;
alter table public.suggestions enable row level security;
alter table public.option_collections enable row level security;
alter table public.result_messages enable row level security;
create policy themes_public_read on public.themes for select using (true);
create policy suggestions_public_read on public.suggestions for select using (true);
create policy collections_public_read on public.option_collections for select using (true);
create policy messages_public_read on public.result_messages for select using (true);

-- API routes verify a Supabase session and enforce ownership server-side.
alter table public.presets enable row level security;
alter table public.newsletter_consents enable row level security;
create policy presets_select_own on public.presets for select using (auth.uid()::text = user_id);
create policy presets_insert_own on public.presets for insert with check (auth.uid()::text = user_id);
create policy presets_delete_own on public.presets for delete using (auth.uid()::text = user_id);
create policy newsletter_consents_select_own on public.newsletter_consents for select using (auth.uid()::text = user_id);
